language: shell

os:
  - osx

before_install:
  - brew update

script:
  - brew audit --debug --verbose --strict --online ./Formula/mlton.rb
  - brew install --debug --verbose ./Formula/mlton.rb
  - brew test --debug --verbose mlton
  - brew uninstall --debug --verbose mlton
