language: shell

os:
  - osx

env:
  - FMLA=mlton-20130715-binary
  - FMLA=mlton-20130715-source

before_install:
  - brew update
  - brew style /dev/null
  - if brew outdated | grep -q gmp; then
      brew upgrade gmp;
    elif ! brew ls | grep -q gmp; then
      brew install gmp;
    fi

script:
  - brew audit --strict --online ./Formula/${FMLA}.rb
  - brew install --verbose ./Formula/${FMLA}.rb
  - brew test --verbose ./Formula/${FMLA}.rb
  - brew unlink --verbose ${FMLA}
  - brew test --verbose ./Formula/${FMLA}.rb
  - brew unlink gmp
  - brew test --verbose ./Formula/${FMLA}.rb
  - brew remove --verbose ${FMLA}
