language: shell

os:
  - osx

before_install:
  - brew update
  - brew style /dev/null

script:
  - brew audit --strict --online ./Formula/mlton.rb
  - brew install --verbose ./Formula/mlton.rb
  - brew test ./Formula/mlton.rb
  - brew remove --verbose mlton
