language: shell

os:
  - osx

before_install:
  - brew update
  - brew style /dev/null
  - if brew outdated | grep -q gmp; then
      brew upgrade gmp
    elif ! brew ls | grep -q gmp; then
      brew install gmp
    fi

script:
  - brew audit --strict --online ./Formula/mlton.rb
  - brew install --verbose ./Formula/mlton.rb
  - brew test --verbose ./Formula/mlton.rb
  - brew remove --verbose mlton
