language: shell

os:
  - osx

before_install:
  - brew update

script:
  - brew audit --strict --online ./Formula/mlton.rb
  - brew install ./Formula/mlton.rb
  - brew test ./Formula/mlton.rb
  - brew uninstall mlton
